# sets generator options.
generator:
  # sets generator features.
  features:
    enable:
      # Enables paths server generation
      - "paths/server"
      # Enables validation of server responses
      - "server/response/validation"

    disable_all: true